import { Link } from 'react-router-dom';
import stats from '../data/stats.json';
import { PageHeader, SectionHeading } from '../components/Shared';
import { formatNumber } from '../utils/display';

export default function Methodology() {
  return <div className="page-enter methodology-page"><PageHeader eyebrow="REFERENCE / METHODOLOGY" title="How to read this research." description="Source, scope, and limitations for interpreting the saved findings and the live evidence database." action={<Link className="button button-outline" to="/evidence">Inspect records ↗</Link>} />
    <div className="method-grid"><div className="method-intro"><span className="eyebrow">THE QUESTION</span><h2>Where does photo search fail when a memory is incomplete?</h2><p>The study collects feedback about Google Photos and isolates complaints about retrieving media from partial cues. It keeps data loss and sync defects visible, but those are not the primary product question.</p></div><div className="method-callout"><span>RESEARCH BOUNDARY</span><p>This is a directional qualitative corpus and a preserved analysis snapshot. It is not a representative survey of all Google Photos users.</p></div></div>
    <section className="content-section"><SectionHeading eyebrow="01 / INPUT" title="Sources and corpus" /><div className="method-cards">{Object.entries(stats.source_counts).sort((a, b) => b[1] - a[1]).map(([name, count]) => <div key={name}><strong>{name}</strong><span>{formatNumber(count)} ingested items</span></div>)}</div><p className="method-caption">Source counts are from the saved ingestion snapshot of {formatNumber(stats.funnel.total_ingested)} items. The read-only database has 12,818 rows, including 10 without a source label.</p></section>
    <section className="content-section"><SectionHeading eyebrow="02 / PROCESS" title="Analysis flow" /><div className="method-steps"><div><span>01</span><h3>Collect</h3><p>Preserved raw feedback from app stores, videos, Reddit, and support discussions.</p></div><div><span>02</span><h3>Filter</h3><p>A saved relevance pass identified {formatNumber(stats.funnel.evaluated_relevant)} relevant complaints.</p></div><div><span>03</span><h3>Classify & cluster</h3><p>The existing pipeline separated vague memory retrieval ({formatNumber(stats.funnel.in_scope)}) from data loss and sync context ({formatNumber(stats.funnel.out_of_scope)}), then grouped patterns.</p></div><div><span>04</span><h3>Synthesize</h3><p>Saved findings connect themes with verbatim quotes and record IDs. No analysis algorithm has been changed for this interface.</p></div></div></section>
    <section className="content-section"><SectionHeading eyebrow="03 / LIMITS" title="Interpretation guardrails" /><div className="limits-list"><div><strong>Snapshot versus database</strong><p>The saved pipeline reports 12,808 ingested items. The database has 12,818 records: 12,808 source-labeled and 10 unlabeled. The aggregate match does not prove the snapshots contain identical records; relevance counts also differ.</p></div><div><strong>Source mix</strong><p>App-store feedback dominates the saved corpus. Counts describe this collected feedback, not the prevalence of a problem among all users.</p></div><div><strong>Emerging clusters</strong><p>Small clusters are observations for further research. Their severity scores are the existing project values, not new prioritization decisions.</p></div><div><strong>Extracted fields</strong><p>Strategy, workaround, and emotional labels are interpretations of complaints. “No workaround text recorded” does not mean no workaround was tried. Ingestion timestamps are not a customer-behavior trend.</p></div><div><strong>Copilot and classifier</strong><p>Evidence Q&A cites database records and abstains when support is insufficient. The separate classifier may return synthetic fallback examples; those are clearly labeled and should not be treated as retrieved evidence.</p></div></div></section>
  </div>;
}
